"""update ChatSession model

Revision ID: 861c970bf9cd
Revises: 
Create Date: 2025-06-03 22:40:43.045418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '861c970bf9cd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('chat_history', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('summary', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_session', schema=None) as batch_op:
        batch_op.drop_column('summary')
        batch_op.drop_column('chat_history')
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
